### ISSUE TITLE
where=0=1 returns results

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-provider-github#29]
http://koop.dc.esri.com/github/chelm/grunt-geo/forks/FeatureServer/0/query?returnGeometry=true&where=0=1 returns features.  

i'd expect it to return none.  i'll take another look once we get @ngoldman's changes incorporated into the sample app.

**Comment by ungoldman** [comment]
hey @jgravois

**Comment by jgravois** [comment]
i'll try and find time to investigate soon.

possibly related: https://github.com/koopjs/koop/issues/291

**Comment by ungoldman** [comment]
may we all find a place where zero equals one

**Comment by dmfenton** [comment]
I would recommend adding a test and fixing the bug here: https://github.com/FeatureServer/FeatureServer

Since this will be replacing the current featureserver implementation (hopefully) soon.

**Comment by jgravois** [comment]
confirmed fixed in koopjs/FeatureServer
